name : First-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello Your Workflow is Executing!!!"
      - name: Printing Githib Logs
        run: echo "${{ toJson(github)}}"
      - name: Print Bye
        run: echo "Workflow is Ended!!"
        
